# 
def get_station_name(station_id):
    station_map = {
        "UIZ": "UAM Iztapalapa",
        "AJU": "Ajusco",
        "ATI": "Atizapan",
        "CUA": "Cuajimalpa",
        "SFE": "Santa Fe",
        "SAG": "San Agustín",
        "CUT": "Cuautitlán",
        "PED": "Pedregal",
        "TAH": "Tlahuac",
        "GAM": "Gustavo A. Madero",
        "IZT": "Iztacalco",
        "CCA": "ICAyCC - UNAM",
        "HGM": "Hospital General de México",
        "LPR": "La Presa",
        "MGH": "Miguel Hidalgo",
        "CAM": "Camarones",
        "FAC": "FES Acatlán",
        "TLA": "Tlalnepantla",
        "MER": "Merced",
        "XAL": "Xalostoc",
        "LLA": "Los Laureles",
        "TLI": "Tultitlán",
        "UAX": "UAM Xochimilco",
        "BJU": "Benito Juárez",
        "MPA": "Milpa Alta",
        "MON": "Montesillo",
        "NEZ": "Nezahualcóyotl",
        "INN": "Investigaciones Nucleares",
        "AJM": "Ajusco Medio",
        "VIF": "Villa de las Flores",
    }
    return station_map.get(station_id, "Station ID not found")
